"""
Base Agent
==========
Shared interface, alert model, and event-processing utilities used by all
surveillance agents in the multi-agent system.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional


logger = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class Alert:
    """A surveillance alert generated by a detection agent."""

    alert_id: str
    agent_name: str
    alert_type: str          # e.g. "SPOOFING", "LAYERING", "PRICE_ANOMALY"
    severity: AlertSeverity
    exchange_id: str
    symbol: str
    detected_at: str         # ISO-8601 UTC
    description: str
    confidence_score: float  # 0.0 – 1.0
    involved_entities: List[str] = field(default_factory=list)
    evidence: Dict[str, Any] = field(default_factory=dict)
    # Cross-agent fields
    case_id: Optional[str] = None
    is_cross_market: bool = False
    related_exchanges: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "alert_id": self.alert_id,
            "agent_name": self.agent_name,
            "alert_type": self.alert_type,
            "severity": self.severity.value,
            "exchange_id": self.exchange_id,
            "symbol": self.symbol,
            "detected_at": self.detected_at,
            "description": self.description,
            "confidence_score": self.confidence_score,
            "involved_entities": self.involved_entities,
            "evidence": self.evidence,
            "case_id": self.case_id,
            "is_cross_market": self.is_cross_market,
            "related_exchanges": self.related_exchanges,
        }


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class BaseAgent:
    """
    Abstract base class for all surveillance agents.

    Agents subscribe to the event bus via ``register_alert_handler``.
    Sub-classes implement ``process_event`` to evaluate individual trading
    events and emit ``Alert`` objects whenever suspicious activity is detected.
    """

    name: str = "BaseAgent"

    def __init__(self) -> None:
        self._handlers: List[Callable[[Alert], None]] = []
        self.alert_count: int = 0
        logger.info("[%s] Initialised.", self.name)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def register_alert_handler(self, handler: Callable[[Alert], None]) -> None:
        """Register a callback that is invoked whenever this agent raises an alert."""
        self._handlers.append(handler)

    def process_event(self, event: Dict[str, Any]) -> None:
        """
        Evaluate a single normalised event dict.

        Sub-classes **must** override this method.  The dict is the JSON-
        serialisable form of ``TradeEvent`` or ``OrderBookEvent`` produced by
        ``exchange_data_simulator.py``.
        """
        raise NotImplementedError

    def process_batch(self, events: List[Dict[str, Any]]) -> None:
        """Process a list of events in order."""
        for event in events:
            self.process_event(event)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _emit_alert(self, alert: Alert) -> None:
        self.alert_count += 1
        logger.warning(
            "[%s] ALERT %s | %s | %s | score=%.2f | %s",
            self.name,
            alert.alert_id,
            alert.exchange_id,
            alert.symbol,
            alert.confidence_score,
            alert.description,
        )
        for handler in self._handlers:
            try:
                handler(alert)
            except Exception:  # pragma: no cover – handler errors must not crash agent
                logger.exception("[%s] Alert handler raised an exception.", self.name)
